### ISSUE TITLE
2 issues

### ISSUE THREAD

**Issue by JokerReaper** [Darkona/AdventureBackpack2#29]
the first issue has to do with changing packs, if not fixable then just warn people about it, when you use the recipes for the other packs, if your items are still in the pack, they will be deleted due to the fact it doesnt transfer the information of what was in the pack like you with see in some mods like iron chests where you change the chest but the contents stay the same.

the 2nd isssue is somewhat of the same out come but much more annoying & problematic, when wearing the back pack & take hits, the packs seem to have a damage bar, & it does have one, the damage is not the problem but i understand why cause of it being in the armor slot, but the items in the pack will be delete upon the moment of it breaking nothing drops from your inventory

i love using your mod its one of the more useful ones & im hoping you will be able to improve & add upon this mod making it better i will continue to use the mod & if i come across any more issues i will be posting them

**Comment by Darkona** [comment]
For the first, I actually warn about it in the recipe section of the wiki.
The second will be fixed soon, because:
1- the backpacks are not supposed to break.
2- They will use a special slot/no slot so they won't take any damage. This is going to be improved soon.

Thanks a lot for the feedback anyway :+1:
