### ISSUE TITLE
Mod Startup Crash 

### ISSUE THREAD

**Issue by SunnyTD** [Darkona/AdventureBackpack2#63]
I think this is a mod compatibility crash. 

Version: adventurebackpack-1.7.10-0.8b
Bug: Crash
Log: http://txt.do/jeua (uploaded for 2 weeks)
Mods: http://txt.do/je7k (uploaded for 2 weeks)

**Comment by MrabEzreb** [comment]
If you take a 5 second look at the crash log, it's something with voxelmap. If it is a compatability thing, then I would say replace voxelmap with a different map mod. I reccomend JourneyMap, or if you want to be more legit, then the mod Antique Atlas.

Also, the issue is with voxelmap AND liteloader. I don't know much about liteloader, but I believe that it isn't very compatable with forge? Not sure though.

**Comment by HyperMan19680** [comment]
I've used this with LiteLoader, and it is fine. I haven't totally tried this with VoxelMap and LL however.
