### ISSUE TITLE
Lots of lag while my backpack is open

### ISSUE THREAD

**Issue by Flexico** [Darkona/AdventureBackpack2#69]
About 85% of the time when I open a backpack, whether I'm wearing it or not, my framerate drops to 2-5 FPS.

**Comment by shivachirr** [comment]
i get this too its kinda annyoing

**Comment by MrabEzreb** [comment]
I made a pull request with a workaround, shift+b puts on/takes off the backpack
Nobody has any idea why this bug happens tho XD
sorry!

**Comment by ElanHR** [comment]
I've been experiencing this but only when accessing it while it's on my back. Accessing it once it's on the ground it works great.

**Comment by shivachirr** [comment]
yup only on the back the lag occurs otherwise evyething else works fine

**Comment by kayila** [comment]
I'm also seeing this bug. It's the only major issue we've seen with the mod and it's currently the main thing holding this mod back from being put into my modpack

**Comment by shivachirr** [comment]
i have it in my modpack mostly using as a tool belt and cosmetic look for
my char

**Comment by marduvGitHub** [comment]
I have the same issue, seems like a rendering bug.
Hope you can fix it! :-)

Let me know if there is some thing I can do to help you track down the cause.

**Comment by mindcloud69** [comment]
I have noticed it as well but for me attempting to use the crafting table in the backpack while its on my back slows it down even further.

**Comment by shivachirr** [comment]
i was able to get this when i open my back pack and got the lag from my log

09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:
java.lang.reflect.InvocationTargetException
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
java.lang.reflect.Method.invoke(Unknown Source)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
Reflector.callVoid(Reflector.java:190)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
net.minecraft.client.renderer.RenderBlocks.func_147800_a(RenderBlocks.java:9260)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:446)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
codechicken.nei.guihook.GuiContainerManager.drawItem(GuiContainerManager.java:187)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
codechicken.nei.guihook.GuiContainerManager.drawItem(GuiContainerManager.java:177)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
codechicken.nei.ItemPanel.draw(ItemPanel.java:129)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
codechicken.nei.LayoutManager.renderObjects(LayoutManager.java:196)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
codechicken.nei.guihook.GuiContainerManager.renderObjects(GuiContainerManager.java:387)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:120)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
weather2.weathersystem.EntityRendererProxyWeather2Mini.func_78480_b(EntityRendererProxyWeather2Mini.java:50)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
net.minecraft.client.main.Main.main(SourceFile:148)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
java.lang.reflect.Method.invoke(Unknown Source)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]:     at
net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[09:18:27] [Client thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by:
java.lang.ArrayIndexOutOfBoundsException

**Comment by shivachirr** [comment]
im starting to think this is more of rendering bug then and other type because i put a tool on my backpack and  get an open gl overflow alert and my screen is messed up

**Comment by kayila** [comment]
That seems like an unrelated bug. It also seems to only affect certain tools

**Comment by penguinsane** [comment]
Just an update, this issue is still present with the most recent version of the mod (beta-0.8b). When the backpack is placed on the ground, it functions just fine. I can get items in and out fine. When I'm wearing it and press B to access, that is when I have massive lag that makes it practically unplayable.

**Comment by Pinaz9** [comment]
I too have this issue. Same as the crazy penguin. As far as I know, it only happens when the bag is on my back.

**Comment by plazia** [comment]
I also have this issue. If I access the bag anywhere it's fine but once I'm wearing it and open up the GUI to display its inventory everything slows to a grinding halt. My FPS drops to like a tenth of what it was.

**Comment by Bolty2** [comment]
it does lag when on back, it's in my private Modpack too.

**Comment by SirWoofie** [comment]
When I open my bag when it's on my back, it will lag for about a minute, and if I attempt to get the backpack off of my back with the button, well, I can't because of the lag. Normally I just crash. Any keybind I don't know of for getting the bag off of my back without using the interface?

**Comment by Darkona** [comment]
Hello people.

To be completely, truly, fully honest with all of you, before I had to leave this in hiatus, I tried to fix that particular problem for like 2 weeks. I don't know why or how it comes to be that it lags so much.

I'll fix it (SOMEHOW) and post an updated version soon ;)

**Comment by Darkona** [comment]
Tentative fix in Beta0.8c
Please confirm

**Comment by CitiesXL2815** [comment]
i will test it the Direwolf20 pack

**Comment by CitiesXL2815** [comment]
yup it's fixed no more lag at all

**Comment by Darkona** [comment]
Ok, time for some closure on this at long last.
I apologize for the extremely long time taken for this fix.
