### ISSUE TITLE
Teleporting Backpacks

### ISSUE THREAD

**Issue by Azougon** [Darkona/AdventureBackpack2#73]
I don't know if this is a bug or not, but when I died above ground I couldn't find my backpack. Then I looked around and remembered that I had dug a cave underneath the place I died. When I went in it I found my backpack. Would it be possible to make them stay on the surface or within a certain distance of the player.

**Comment by Jossydelrosal** [comment]
Actually, I have the exact same problem. And since I also have Zelda Sword skills installed (which generates thousands of random dungeons underground) I've lost it quite a frustrating amount of times. I think a Config OPTION to DISABLE DEATH PLACING OF BACKPACK would be extremely useful. (I use keep inventory = true in my worlds, so I don't need the whole "Backpack stays even if you die" thing.

**Comment by Darkona** [comment]
I have changed the death placement algorith so it is a little more sane. That said, this guarantees your backpack will be placed.
